# run.ps1 auto-generated by EasyAzureFunction module, https://github.com/iricigor/EasyAzureFunction, iricigor@gmail.com
'run.ps1 start'

# POST method: $req
$requestContent = Get-Content $req -Raw
try {
  $requestBody = $requestContent | ConvertFrom-Json
  $Failed = $false
  "Params (JSON): $($requestBody.PSObject.Properties.Name -join `",`")"
  $EzInvokeCommand = $requestBody.EzInvokeCommand
  $EzName = $requestBody.EzName
  $EzPSProvider = $requestBody.EzPSProvider
  $EzRoot = $requestBody.EzRoot
  $EzDescription = $requestBody.EzDescription
  $EzScope = $requestBody.EzScope
  $EzPersist = $requestBody.EzPersist
  $EzCredential = $requestBody.EzCredential
  $EzUseTransaction = $requestBody.EzUseTransaction
} catch {$Failed = $true}
if ($Failed) {
"Params (URLEncoded): $requestContent"
  $requestContent -split '&' | % {
    $v = $_ -split '='
    if ($v[1]) {Set-Variable -Name $v[0] -Value $v[1]}
  }
}

# prepare output, either default web-page or invoke command
cd $EXECUTION_CONTEXT_FUNCTIONDIRECTORY
if (!$EzInvokeCommand) {
  'show default web page'
  $Output = Get-Content .\index.html -Raw
} else {
  'invoke command'
  try {
    $ParamsHash = @{}
    $CredentialArray = ''
    if ($EzName) {$ParamsHash.Add('Name',$EzName)}
    if ($EzPSProvider) {$ParamsHash.Add('PSProvider',$EzPSProvider)}
    if ($EzRoot) {$ParamsHash.Add('Root',$EzRoot)}
    if ($EzDescription) {$ParamsHash.Add('Description',$EzDescription)}
    if ($EzScope) {$ParamsHash.Add('Scope',$EzScope)}
    if ($EzPersist) {$ParamsHash.Add('Persist',$True)}
    if ($EzCredentialUserName -and $EzCredentialPassword) {
      EzCredentialSecPass = ConvertTo-SecureString '$EzCredentialPassword' -AsPlainText -Force
      EzCredential = New-Object System.Management.Automation.PSCredential ('$EzCredentialUserName', $EzCredentialSecPass)
      $CredentialArray += ' -Credential $EzCredential'
    if ($EzUseTransaction) {$ParamsHash.Add('UseTransaction',$True)}
    "Params: $($ParamsHash.Keys -join `",`")"
    $Output = New-PSDrive @ParamsHash | Out-String
    Get-ChildItem AzFC:\ | OutString
    if ($Output) {$Color = 'white'}
    else {$Color = 'gray'; $Output = 'Command run successfully, but it returned no output'}
  } catch {
    $Output = $_
    $Color = 'red'
  }
  $Head = "<head><style>body {background-color: #012456; color: $Color;}</style><title>EasyAzureFunction - New-PSDrive running example</title></head>"
  $Back = '<p><a href="javascript:history.back()" style="color:yellow;">Go Back</a></p>'
  $Output = $Head + '<pre>' + $Output + $Back + '</pre>'
  $Output = $Output -replace "`n",'</br>'
}

# parse and send back output
$Output2 = [PSCustomObject]@{Status = 200; Body = '';  Headers = @{}}
$Output2.Headers.Add('content-type','text/html')
$Output2.Body = $Output -replace '"',"'"

Out-File -Encoding utf8 -FilePath $res -inputObject ($Output2 | ConvertTo-JSON)
