function Convert-ParametersToRunner {
    
    # Used to generate run.ps1 file which is executed in Azure Function

    param (
        
        [string[]]$Command,
        [switch]$Invoke,
        [switch]$Clipboard

    )

    BEGIN {
        $Response = @()
        # TODO: Add some info how file was generated?
        $Response += "# run.ps1 auto-generated by EasyAzureFunction module, iricigor@gmail.com","'run.ps1 start'"
    }

    PROCESS {

        foreach ($C1 in $Command) {
            Write-Verbose -Message "Processing command $C1"
            $Params = Get-Parameters $C1 | Select -Expand Name -Unique

            # generate code to read parameters

            # According to documentation / template POST should give me json formatted parameters, but I got them HTML encoded like Igor=1&Joey=2
            # $Response += '', '# POST method: $req', '$requestBody = Get-Content $req -Raw | ConvertFrom-Json'
            # $Response += "`$InvokeCommand = `$requestBody.InvokeCommand" # reads hidden parameter
            # foreach ($P1 in $Params) {
            #     $Response += "`$$P1 = `$requestBody.$P1"  # output like $url = $req_query_url
            # }

            $Response += '', '# POST method: $req', '$requestBody = Get-Content $req -Raw'
            $Response += "`$requestBody -split '&' | % {","  `$v = `$_ -split '='","  Set-Variable -Name `$v[0] -Value `$v[1]","}"
        }

        # generate code to open default page
        $Response += '','# prepare output, either default web-page or invoke command'
        $Response += 'if (!$InvokeCommand) {',"  'show default web page'", '  cd $EXECUTION_CONTEXT_FUNCTIONDIRECTORY', '  $Output = Get-Content .\index.html -Raw'
        # TODO: Evaluate if page should be called index.html, or index.CommandName.html

        # generate code to invoke command in try catch block, using parameters splatting
        $Response += '} else {',"  'invoke command'", '  try {'
        $Response += "    `$ParamsHash = @{}"
        foreach ($P1 in $Params) {
            $Response += "    if (`$$P1) {`$ParamsHash.Add('$P1',`$$P1)}"
        }
        $Response += "    `$Output = $C1 @ParamsHash | Out-String"
        $Response += '  } catch {','    $Output = $_','  }' # FIXME: Not really working, error crashes web app
        # TODO: Add some differentiation of output, i.e. error to be red

        $Response += "  `$Output = '<pre>' + `$Output + '</pre>'","  `$Output = `$Output -replace `"``n`",'</br>'",'}'
        
        
        # convert output to HTML and parse it back
        $Response += '', '# parse and send back output'
        $Response += "`$Output2 = [pscustomobject]@{Status = 200; Body = '';  Headers = @{}}","`$Output2.Headers.Add('content-type','text/html')"
        $Response += "`$Output2.Body = `$Output -replace '`"',`"'`""

        $Response += 'Out-File -Encoding utf8 -FilePath $res -inputObject $Output2'

    }

    END {
        if ($Clipboard) {
            $Response | Set-Clipboard
        } elseif ($Invoke) {
            $TempFile = [System.IO.Path]::GetTempFileName() + '.txt'
            $Response | Out-File $TempFile
            Invoke-Item $TempFile
        } else {
            $Response
        }
    }
}